# SPDX-FileCopyrightText: Copyright (c) 2023 Yegor Bugayenko
# SPDX-License-Identifier: MIT

[package]
name = "emap"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/yegor256/emap"
description = "A map with a fixed capacity and integers as keys"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/yegor256/emap"
keywords = ["memory", "map"]
categories = ["data-structures", "memory-management"]

[dependencies]
serde = { version = "1.0.185", optional = true, default-features = false }

[dev-dependencies]
bincode = "1.3.3"
paste = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "with_capacity"
harness = false
